version: "3"

services:
  api:
    build: .
    restart: always
    tty: true
    environment:
      - SURREALDB_URL=http://surrealdb:8000
      - SURREALDB_WS=ws://surrealdb:8000/rpc
      - SURREALDB_USER=root
      - SURREALDB_PASS=root
    ports:
      - 8080:8000
    volumes:
      - .:/home

  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    command: "start --user root --pass root file://database.db"
    volumes:
      - ./database.db:/database.db
