version: "3"

services:
  api:
    build: .
    tty: true
    ports:
      - 8080:5000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app:rw

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data: