version: "3"

services:
  api:
    build: .
    restart: always
    tty: true
    environment:
      - PROJECT_ID=
      - GOOGLE_APPLICATION_CREDENTIALS=/home/serviceAccount.json
    ports:
      - 8080:8000
    volumes:
      - .:/home
