version: "3"

services:
  api:
    build: .
    tty: true
    ports:
      - 8080:5000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/home
    command: bash

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgweb:
    image: 'sosedoff/pgweb:latest'
    environment:
      DATABASE_URL: postgres://root:passw0rd@db:5432/postgres?sslmode=disable
    depends_on:
      - db
    ports:
      - 8081:8081
    command: ["sh", "-c", "sleep 3; /usr/bin/pgweb --bind=0.0.0.0 --listen=8081"]

volumes:
    postgres_data: